# Generated by Django 5.1.2 on 2024-11-02 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Js',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctQ1', models.IntegerField(default=0)),
                ('timeQ1', models.FloatField(default=0)),
                ('correctQ2', models.IntegerField(default=0)),
                ('timeQ2', models.FloatField(default=0)),
                ('profile_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('certificates', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
