# Generated by Django 5.1.2 on 2024-11-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsTutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='js',
            name='correctQ1',
        ),
        migrations.RemoveField(
            model_name='js',
            name='correctQ2',
        ),
        migrations.RemoveField(
            model_name='js',
            name='timeQ1',
        ),
        migrations.RemoveField(
            model_name='js',
            name='timeQ2',
        ),
    ]
