# Generated by Django 5.1.2 on 2024-10-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0004_rename_correct_school_correctq1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
