# Generated by Django 5.1.2 on 2024-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0005_school_certificate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='certificate_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
