# Generated by Django 5.1.2 on 2024-10-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0006_alter_school_certificate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='certificate_name2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='correctQ3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='timeQ3',
            field=models.FloatField(default=0),
        ),
    ]
