# Generated by Django 5.1.2 on 2024-10-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0007_school_certificate_name2_school_correctq3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='certificate_name2',
        ),
        migrations.RemoveField(
            model_name='school',
            name='correctQ3',
        ),
        migrations.RemoveField(
            model_name='school',
            name='timeQ3',
        ),
    ]
