# Generated by Django 5.1.2 on 2024-10-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0008_remove_school_certificate_name2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='certificate_name',
        ),
        migrations.AddField(
            model_name='school',
            name='certificates',
            field=models.JSONField(default=list),
        ),
    ]
