# Generated by Django 5.1.2 on 2024-10-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0009_remove_school_certificate_name_school_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='certificates',
        ),
        migrations.AddField(
            model_name='school',
            name='certificate_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
