# Generated by Django 5.1.2 on 2024-10-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0010_remove_school_certificates_school_certificate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='certificates',
            field=models.JSONField(default=list),
        ),
    ]
