# Generated by Django 5.1.2 on 2024-10-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0011_school_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='certificates',
            field=models.JSONField(default=[]),
        ),
    ]
