# Generated by Django 5.1.2 on 2024-10-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0023_alter_school_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='profile_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
