# Generated by Django 5.1.2 on 2024-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0026_alter_school_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='corrects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='finals',
            field=models.JSONField(default=list),
        ),
    ]
