# Generated by Django 5.1.2 on 2024-11-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0027_school_corrects_school_finals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='certificate_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='correctQ1',
        ),
        migrations.RemoveField(
            model_name='school',
            name='correctQ2',
        ),
        migrations.RemoveField(
            model_name='school',
            name='corrects',
        ),
        migrations.RemoveField(
            model_name='school',
            name='finals',
        ),
        migrations.RemoveField(
            model_name='school',
            name='timeQ1',
        ),
        migrations.RemoveField(
            model_name='school',
            name='timeQ2',
        ),
    ]
