# Generated by Django 5.1.2 on 2024-11-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myexam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='owner',
        ),
    ]
