# Generated by Django 5.1.2 on 2024-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certificates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
