# Generated by Django 5.1.2 on 2024-10-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='certificates',
        ),
    ]
